### ISSUE TITLE
제안서 리뷰

### ISSUE THREAD

**Issue by MisooKim2** [yugmldnjs/C202309-P#1]
1. 비밀번호 추천 알고리즘에 대한 부분을  향후 구체적으로 작성하시길 바랍니다.
- 변경 사항은 제안서는 수정하지 마시고, 1차 진척보고서에 반영하여 주시길 바랍니다

**Comment by yugmldnjs** [comment]
1차 진척보고서에 비밀번호 추천 알고리즘 작성 완료 했습니다.
